
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
spring:
  server:
    port: 50798
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger.html
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/users
      username: root
      password: root
