server:
  port: 50798
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
