server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id : auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true
jwt:
  secret: 6500703933252323237012948208681463081259978395
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10